### ISSUE TITLE
Оновлення стану ПЗ до стану upstream

### ISSUE THREAD

**Issue by Andygol** [osm-ua/osm-tasking-manager2#1]
- [x] @andygol - оновити ПЗ в репозиторії до останньої поточної версії upstream + добавки від @edward17
- [x] @tdyoma  - оновити код на http://tasks.openstreetmap.org.ua/

**Comment by Edward17** [comment]
Извините, если не туда пишу.

Несколько дней назад поигрался с переводом OSM TM на украинский здесь:

https://www.transifex.com/projects/p/osm-tasking-manager2/viewstrings/#uk/master/28435512

Перевёл строки, которые раньше не имели перевода, и внёс немного исправлений.

Можно ли эти изменения как-нибудь перенести на украинский Tasking Manager?

P. S. Или это уже сделано?

**Comment by Andygol** [comment]
@Edward17 
Якщо переклад був зроблений до 16/06/15 - https://github.com/hotosm/osm-tasking-manager2/pull/658, то все є, якщо після - то треба додавати вручну

**Comment by Edward17** [comment]
@Andygol 
я это делал 17 июня.

**Comment by Andygol** [comment]
@osm-ua/owners 
додано нові шари: Mapbox та Укрортофто
додано іконку на кнопку вибору шарів

То ж, закриваю

**Comment by Edward17** [comment]
@Andygol 
К сожалению, в Chrome и Internet Explorer (на Windows) нет иконки на кнопке выбора слоёв.

**Comment by Andygol** [comment]
@Edward17 
спробуй почисти кеш

**Comment by Edward17** [comment]
@Andygol 
Не помогает.

Но эта проблема не критична.

**Comment by Andygol** [comment]
@Edward17 
У мене так

![image](https://cloud.githubusercontent.com/assets/369696/8290206/1f7babe4-192a-11e5-91a0-ece2b8083b10.png)

**Comment by tdyoma** [comment]
В мене так як і в @Andygol. Видно в Chrome i Safari

**Comment by Edward17** [comment]
@Andygol @tdyoma 
:(

![image](https://cloud.githubusercontent.com/assets/11292985/8290315/f12bb85a-192a-11e5-9e35-6bef1433c7ae.png)

**Comment by tdyoma** [comment]
Ctrl+R не допомагає? В мене якраз після цього стало все ок

**Comment by Edward17** [comment]
А на мобильном Chrome всё ОК...

![screenshot](https://cloud.githubusercontent.com/assets/11292985/8290858/473cdfdc-192e-11e5-8d64-d205c2221374.png)

@tdyoma завтра попробую.

**Comment by Edward17** [comment]
@tdyoma 
неа, не помогает.

Ну и ладно.

**Comment by pavlo-dudka** [comment]
Потрібно взяти layers.png з https://github.com/Leaflet/Leaflet/tree/master/dist/images і скопіювати в https://github.com/osm-ua/osm-tasking-manager2/tree/master/osmtm/static/js/lib/images
В https://github.com/osm-ua/osm-tasking-manager2/blob/7e2edb3b1e8165a4b9354e50bd541b8ce32b7a58/osmtm/static/js/lib/leaflet.css є посилання і на layers.png і на layers-2x.png

**Comment by tdyoma** [comment]
Підтверджую багу на вінді, у мене не показується :(

**Comment by Andygol** [comment]
c2e77e5f85b89ab9ddaf7f1897e00360a7d60d53 - виправлено

**Comment by Edward17** [comment]
@Andygol 
На Windows в Chrome и Internet Explorer иконка есть.

Большое спасибо!
