### ISSUE TITLE
Мінімапа з Україною замість всього світу

### ISSUE THREAD

**Issue by Andygol** [osm-ua/osm-tasking-manager2#3]
Заміна мінімапи всього світу на мінімапу України:
- [ ] треба поправити top i left тут: https://github.com/osm-ua/osm-tasking-manager2/blob/7e2edb3b1e8165a4b9354e50bd541b8ce32b7a58/osmtm/templates/project.mako#L33
- [x] world_map.png замінити на свою картинку тут: https://github.com/osm-ua/osm-tasking-manager2/blob/7e2edb3b1e8165a4b9354e50bd541b8ce32b7a58/osmtm/static/css/main.css#L5513

**Comment by pavlo-dudka** [comment]
Спробуй формули для top і left замінити на такі:
left = (centroid.x - coordMin.x) \* imageWidth / (coordMax.x - coordMin.x) - 1
top = (-centroid.y + coordMax.y) \* imageHeight / (coordMax.y - coordMin.y) - 1
де
coordMin, coordMax -- координати кутів прямокутника України
imageWidth, imageHeight - ширина і висота картинки в пікселях

**Comment by Andygol** [comment]
Зображення для мінімапи (6-зум)
![image](https://cloud.githubusercontent.com/assets/369696/8301898/ed44315c-199a-11e5-9a27-7f8df2dbe101.png)

5-й зум
![image](https://cloud.githubusercontent.com/assets/369696/8301957/5f7d9ac4-199b-11e5-991f-f403c3c78ffc.png)

**Comment by Andygol** [comment]
https://github.com/osm-ua/osm-tasking-manager2/tree/ukr-minimap - гілка для роботи над мінімапою

**Comment by Andygol** [comment]
координати  України (44.00, 21.00)  - (53.00, 41.00)

**Comment by Andygol** [comment]
Щось наколупав - fa0ce6ea25614d9c176ce258b7fb68a120ae8f11

але не зовсім задоволений результатом.

На головній маркер на мінімапі розташовується не там де треба :cry: 
![image](https://cloud.githubusercontent.com/assets/369696/8317771/74b4e84e-1a08-11e5-8af0-5b6f68015e62.png)

В самих проектах все добре :+1: 
![image](https://cloud.githubusercontent.com/assets/369696/8317778/8a11d35a-1a08-11e5-8bc5-02dde527f478.png)

**Comment by pavlo-dudka** [comment]
Перевір координати кутів прямокутника, вони очевидно інакші ніж 21,44 - 41,53

**Comment by Andygol** [comment]
Нова ідея - https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-minimap/
