### ISSUE TITLE
Не працює автентифікація

### ISSUE THREAD

**Issue by tdyoma** [osm-ua/osm-tasking-manager2#4]
Не працює логін через OSM. Не вантажиться сторінка :( http://tasks.openstreetmap.org.ua/login

**Comment by Andygol** [comment]
@tdyoma схоже, що перезавантаження серверу допомоголо
![osm tasking manager - 2015-11-09 19-49-15](https://cloud.githubusercontent.com/assets/369696/11041527/025a9214-871b-11e5-946c-f26fd44b20d2.png)
